import IISKandidaty_na_rabotu_v_organizaciyuПланирСобесEController from '../i-i-s-kandidaty-na-rabotu-v-organizaciyu-планир-собес-e';

var IISKandidaty_na_rabotu_v_organizaciyuПланирСобесENewController = IISKandidaty_na_rabotu_v_organizaciyuПланирСобесEController;
export default IISKandidaty_na_rabotu_v_organizaciyuПланирСобесENewController;
