import IISKandidaty_na_rabotu_v_organizaciyuРегРезультEController from '../i-i-s-kandidaty-na-rabotu-v-organizaciyu-рег-результ-e';

var IISKandidaty_na_rabotu_v_organizaciyuРегРезультENewController = IISKandidaty_na_rabotu_v_organizaciyuРегРезультEController;
export default IISKandidaty_na_rabotu_v_organizaciyuРегРезультENewController;
