import IISKandidaty_na_rabotu_v_organizaciyuРегистАнкетыEController from '../i-i-s-kandidaty-na-rabotu-v-organizaciyu-регист-анкеты-e';

var IISKandidaty_na_rabotu_v_organizaciyuРегистАнкетыENewController = IISKandidaty_na_rabotu_v_organizaciyuРегистАнкетыEController;
export default IISKandidaty_na_rabotu_v_organizaciyuРегистАнкетыENewController;
