import IISKandidaty_na_rabotu_v_organizaciyuСотрудникиEController from '../i-i-s-kandidaty-na-rabotu-v-organizaciyu-сотрудники-e';

var IISKandidaty_na_rabotu_v_organizaciyuСотрудникиENewController = IISKandidaty_na_rabotu_v_organizaciyuСотрудникиEController;
export default IISKandidaty_na_rabotu_v_organizaciyuСотрудникиENewController;
