//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kandidaty_na_rabotu_v_organizaciyu
{
    
    
    /// <summary>
    /// Class for determinate objects assembly in DI.
    /// </summary>
    public class ObjectsMarker
    {
    }
}
